///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FavoriteDataLinks {
/*
{
  "url": null,
  "label": "&laquo; السابق",
  "active": false
} 
*/

  String? url;
  String? label;
  bool? active;

  FavoriteDataLinks({
    this.url,
    this.label,
    this.active,
  });
  FavoriteDataLinks.fromJson(Map<String, dynamic> json) {
    url = json['url']?.toString();
    label = json['label']?.toString();
    active = json['active'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    data['label'] = label;
    data['active'] = active;
    return data;
  }
}

class FavoriteDataData {
/*
{
  "id": 4,
  "facility_id": 1,
  "student_id": 1,
  "created_at": "2022-01-30T11:11:24.000000Z",
  "name": "مدرستي الجميلة",
  "rate": "0",
  "address": "المملكة العربية السعودية - الرياض",
  "city": "الرياض",
  "logo": "https://dev17.toplinedev.com/theedukey/public/uploads/facilities/16433029182118.jpg"
} 
*/

  int? id;
  int? facilityId;
  int? studentId;
  String? createdAt;
  String? name;
  String? rate;
  String? address;
  String? city;
  String? logo;

  FavoriteDataData({
    this.id,
    this.facilityId,
    this.studentId,
    this.createdAt,
    this.name,
    this.rate,
    this.address,
    this.city,
    this.logo,
  });
  FavoriteDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    facilityId = json['facility_id']?.toInt();
    studentId = json['student_id']?.toInt();
    createdAt = json['created_at']?.toString();
    name = json['name']?.toString();
    rate = json['rate']?.toString();
    address = json['address']?.toString();
    city = json['city']?.toString();
    logo = json['logo']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['facility_id'] = facilityId;
    data['student_id'] = studentId;
    data['created_at'] = createdAt;
    data['name'] = name;
    data['rate'] = rate;
    data['address'] = address;
    data['city'] = city;
    data['logo'] = logo;
    return data;
  }
}

class FavoriteData {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 4,
      "facility_id": 1,
      "student_id": 1,
      "created_at": "2022-01-30T11:11:24.000000Z",
      "name": "مدرستي الجميلة",
      "rate": "0",
      "address": "المملكة العربية السعودية - الرياض",
      "city": "الرياض",
      "logo": "https://dev17.toplinedev.com/theedukey/public/uploads/facilities/16433029182118.jpg"
    }
  ],
  "first_page_url": "https://dev17.toplinedev.com/theedukey/public/api/student-auth/favorites?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "https://dev17.toplinedev.com/theedukey/public/api/student-auth/favorites?page=1",
  "links": [
    {
      "url": null,
      "label": "&laquo; السابق",
      "active": false
    }
  ],
  "next_page_url": null,
  "path": "https://dev17.toplinedev.com/theedukey/public/api/student-auth/favorites",
  "per_page": 10,
  "prev_page_url": null,
  "to": 1,
  "total": 1
} 
*/

  int? currentPage;
  List<FavoriteDataData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  List<FavoriteDataLinks?>? links;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  FavoriteData({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.links,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  FavoriteData.fromJson(Map<String, dynamic> json) {
    currentPage = json['current_page']?.toInt();
    if (json['data'] != null) {
      data = List<FavoriteDataData>.from(
          json['data'].map((model) => FavoriteDataData.fromJson(model)));
    }
    firstPageUrl = json['first_page_url']?.toString();
    from = json['from']?.toInt();
    lastPage = json['last_page']?.toInt();
    lastPageUrl = json['last_page_url']?.toString();
    if (json['links'] != null) {
      links = List<FavoriteDataLinks>.from(
          json['links'].map((model) => FavoriteDataLinks.fromJson(model)));
    }
    nextPageUrl = json['next_page_url']?.toString();
    path = json['path']?.toString();
    perPage = json['per_page']?.toInt();
    prevPageUrl = json['prev_page_url']?.toString();
    to = json['to']?.toInt();
    total = json['total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['current_page'] = currentPage;
    if (this.data != null) {
      data['data'] = this.data?.map((v) => v?.toJson()).toList();
    }
    data['first_page_url'] = firstPageUrl;
    data['from'] = from;
    data['last_page'] = lastPage;
    data['last_page_url'] = lastPageUrl;
    if (links != null) {
      data['links'] = links?.map((e) => e?.toJson()).toList();
    }
    data['next_page_url'] = nextPageUrl;
    data['path'] = path;
    data['per_page'] = perPage;
    data['prev_page_url'] = prevPageUrl;
    data['to'] = to;
    data['total'] = total;
    return data;
  }
}

class Favorite {
/*
{
  "status": true,
  "data": {
    "current_page": 1,
    "data": [
      {
        "id": 4,
        "facility_id": 1,
        "student_id": 1,
        "created_at": "2022-01-30T11:11:24.000000Z",
        "name": "مدرستي الجميلة",
        "rate": "0",
        "address": "المملكة العربية السعودية - الرياض",
        "city": "الرياض",
        "logo": "https://dev17.toplinedev.com/theedukey/public/uploads/facilities/16433029182118.jpg"
      }
    ],
    "first_page_url": "https://dev17.toplinedev.com/theedukey/public/api/student-auth/favorites?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "https://dev17.toplinedev.com/theedukey/public/api/student-auth/favorites?page=1",
    "links": [
      {
        "url": null,
        "label": "&laquo; السابق",
        "active": false
      }
    ],
    "next_page_url": null,
    "path": "https://dev17.toplinedev.com/theedukey/public/api/student-auth/favorites",
    "per_page": 10,
    "prev_page_url": null,
    "to": 1,
    "total": 1
  }
} 
*/

  bool? status;
  FavoriteData? data;

  Favorite({
    this.status,
    this.data,
  });
  Favorite.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    data = (json['data'] != null) ? FavoriteData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['data'] = this.data!.toJson();
    return data;
  }
}
