const Map<String, String> ar = {
  // dio error messages
  "Request to API server was cancelled": "تم إلغاء طلب الخادم ",
  "Connection timeout with API server": " انتهت مهلة الاتصال مع الخادم",
  "Connection to API server failed due to internet connection":
      "فشل الاتصال  بسبب اتصال الإنترنت",
  "Receive timeout in connection with API server":
      " انتهت مهلة الاستلام في الاتصال مع الخادم ",
  "Send timeout in connection with API server":
      " انتهت مهلة الإرسال في الاتصال مع الخادم ",
  "Something went wrong": "حدث خطأ ما",

  // login page
  'login': 'تسجيل دخول',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'forget': "نسيت كلمة المرور؟",
  'signUp': 'تسجيل حساب جديد',
  'enter': 'دخول',
  'skip': 'تخطي',
  'account_deleted': ' حذف الحساب',
  'account_deleted_successfully': 'تم حذف الحساب بنجاح',
  'delete_account_desc': 'هل أنت متأكد من حذف حسابك؟',
  "password or email is wrong": "كلمة المرور أو البريد الإلكتروني غير صحيحة",

  // signUp page
  'name_ar': 'الإسم الثلاثي',
  'name_en': 'الإسم الثلاثي باللغة الإنجليزية',
  'mobile': 'رقم اتصال جوال',
  'phone': 'رقم الهاتف',
  'city': 'المدينة',
  'choose_city': 'اختر المدينة',
  'password_confirm': 'تأكيد كلمة المرور',
  'Password is not match': 'كلمة المرور غير متطابقة',
  'Name is not valid': 'الأسم غير صحيح',
  'terms approve': 'انا اوافق على الشروط والأحكام',
  'Email is not valid': 'البريد الإلكتروني غير صالح',
  'Mobile is not valid': 'رقم الجوال غير صالح',
  'Phone is not valid': 'رقم الهاتف غير صالح',
  'Password is require': 'كلمة المرور يجب ان تكون اكثر من 8 خانات',
  "don't_have_an_account": ' ليس لديك حساب ؟',
  'have_an_account': 'لديك حساب ؟ ',
  "terms": "الشروط والأحكام",
  "you_must_agree_TOS": "يجب الموافقة على الشروط والاحكام",
  "you_must_select_city": "يجب اختيار المدينة",
  // forget pass
  'remember_pass': 'تذكرت كلمة المرور ؟ ',

// edit profile
  'old_password': 'كلمة المرور القديمة',
  'profile_updated': 'تم تحديث الملف الشخصي',
  // home
  'search_about': 'ابحث عن ',
  'Please_select_the_educational_stage': 'من فضلك اختر المرحلة التعليمية',
  'school_name': 'اسم المدرسة',
  'search': 'بحث',
  'about_us': 'من نحن',
  // menu
  'home': 'الرئيسية',
  'notifications': 'الاشعارات',
  'edit_profile': 'تعديل الملف الشخصي',
  'favorite': 'المفضلة',
  'my_orders': 'طلباتي',
  'offers': 'أنشطة وبرامج ترفيهية',
  'sons': 'الأبناء',
  'language': 'اللغات',
  'contact_us': 'اتصل بنا',
  'logout': 'تسجيل الخروج',
  "guest": "زائر",

  // contactUs
  'title': 'عنوان الرسالة',
  'body': 'محتوى الرسالة',
  'text_length': 'يجب ان يكون طول النص اكثر من 10 احرف',
  "send_success": "تم ارسال الرسالة بنجاح",
// favorite

  'delete_favorite_success': 'تم الحذف من المفضلة',
  // son
  'id_number': 'رقم الهوية',
  'birth_date': 'تاريخ الميلاد',
  'name': 'الإسم',
  'manage_son_description':
      'من خلال إدارة الابناء يمكنك اضافة اطفالك للاشتراك في الخدمات التي تقدمها المنصة',
  'certificate_image': 'صورة اخر شهادة علمية',
  'edit_certificate_image': 'تعديل صورة آخر شهادة علمية',
  'certificate_image is not valid': 'يجب ادخال صورة الشهادة',

  'id_image': 'صورة الهوية',
  'edit_id_image': 'تعديل صورة الهوية',
  'id_image is not valid': 'يجب ادخال صورة الهوية',
  'family_id_image': 'صورة بطاقة العائلة',
  'edit_family_id_image': 'تعديل صورة بطاقة العائلة',

  'add_son': "اضافة ابن/ة",
  'male': 'ذكر',
  'female': 'انثى',
  'gender': 'جنس الابن/ة',
  'son_id': 'رقم هوية الابن/ة',
  'personal_image': 'الصوره الشخصية',
  'edit_personal_image': 'تعديل الصوره الشخصية ',
  'personal_image is not valid': 'يجب ادخال صورة الشخصية ',
  "add_family_id_image": "اضافة صورة بطاقة العائلة",
  'birth_date is not valid': 'يجب ادخال تاريخ الميلاد',
  'id is not valid': 'رقم الهوية غير صالح',
  'add_son_success': 'تم اضافة الابن/ة بنجاح',
  'edit_son_success': 'تم تعديل الابن/ة بنجاح',
  'delete_son_success': 'تم حذف الابن/ة بنجاح',
  'add': 'اضافة',
  'edit_picture': 'تعديل الصورة',
  'edit_son': 'تعديل بيانات الابن/ة',
  "family_id_not_found": "يجب اضافة بطاقة العائلة اولا",
// orders
  'success': 'رسالة تأكيد',
  'payment_success': 'تمت العملية بنجاح',
  'error': 'خطأ',

  'orderNum': 'رقم الطلب',
  'serviceProvider': 'مقدم الخدمة',
  'orderStatus': 'الحالة',
  'serviceName': 'اسم الخدمة ',
  'stage': 'المرحلة التعليمية',
  'theClass': 'الصف الدراسي ',
  'subscriptionTypr': 'نوع الاشتراك',
  'priceAfterDiscount': 'السعر بعد الخصم',
  'priceBeforeDiscount': 'السعر قبل الخصم',
  "is_tmara_enabled": "الدفع من خلال تمارا؟",

  'pay': 'الدفع',
  "payment_methods": "طرق الدفع",
  "choose_payment_method": "انقر على طريقة الدفع المناسبة",
  "payment_failed": " فشل الدفع",
  "payment_canceled": "تم الغاء الدفع",
  "pay_with_payTab": " دفع بواسطة بيتاب",
  "pay_with_tmara": "دفع بواسطة تمارا",
// order status
  "is_paid": "مدفوع",
  "new": "جديد",
  "accepted": "بنتظار الدفع",
  "under_revision": "تحت المراجعة",
  "rejected": "مرفوض",

// search screen
  'search_results': 'نتائج البحث',
  'show_results_on_map': 'عرض على الخريطة',
  'search_results_for': ' نتائج البحث عن :',
  'payment_method': 'طريقة الدفع',
  'ratings': 'التقييمات',
  'all': 'الكل',
  'press_to_view_details': 'اضغط لمشاهدة التفاصيل',
  // school details
  'school_details': 'تفاصيل المدرسة',
  'school_gallery': 'معرض الصور',
  'note': 'ملاحظات',
  'subscribe_now': 'اشترك الآن',
  "related_schools": 'منشآت ذات صلة',
  'Please_select_the_child': 'يرجى اختيار الطفل',
  'continue_and_add_sons': 'متابعة واضافة ابناء',
  'also_you_can': 'او يمكنك ايضا',
  'added_to_favorite': 'تم اضافة المنشأة الى المفضلة',
  'removed_from_favorite': 'تم حذف المنشأة من المفضلة',
  "continue_with_main_account": 'متابعة بالحساب الرئيسي',
  "confirm_continue_with_son": 'التأكيد بالمتابعة باختيار الطفل ؟',

  'subscriber_info': 'بيانات المشترك',
  "subscription_package": 'باقة الاشتراك',
  'Order_added_successfully': 'تم اضافة الطلب بنجاح',
  'confirm': 'تأكيد',
  'confirm_continue_with_main_account': 'هل تريد المتابعة بالحساب الرئيسي؟',
  // other
  'cancel': 'الغاء',
  'submit': 'ارسال',
  'edit': 'تعديل',
  'delete': 'حذف',
  'gallery': 'معرض الصور',
  'add_photo': 'اضف صورة',
  'camera': 'الكاميرا ',
  'empty_results': 'لا يوجد نتائج',
  "please_review_all_fields": "يرجى مراجعة البيانات المٌدخلة",
  'currency': ' ريال سعودي ',
  'OK': 'حسنا',
  "FirstPageException_title": "حدث خطأ ما",
  "FirstPageException_message": 'واجه التطبيق خطأ غير معروف\n'
      'فضلا حاول لاحقاً',
  "try_again": "اعد المحاولة",

  'from': 'من',
  'to': 'إلى',
  'you_must_signin_to_access_to_this_section':
      'يجب تسجيل الدخول للوصول إلى هذه الصفحة',
  "yes": "نعم",
  "no": "لا",
  "after_discount": "بعد الخصم",
  "before_discount": "قبل الخصم",
  "show_more": "  عرض المزيد  ",
  "show_less": "  أخفاء المزيد ",

  "no_other_results": "لا يوجد نتائج اخرى",
  "no_results": "لا يوجد نتائج",

  "Phone Verification": "تفعيل الهاتف",
  'OTP Code': 'رمز التفعيل',
  "Verify": "تفعيل",
  "Resend the OTP Code Again": "إعادة إرسال رمز التفعيل",
  "We sent the OTP code to your phone, please check it and enter below":
      "تم إرسال رمز التفعيل إلى هاتفك، يرجى التحقق منه وإدخاله أدناه",
  "invalid_phone_number": "رقم الهاتف غير صحيح",
  "invalid-credential": "رمز التفعيل غير صحيح او منتهي الصلاحية",
  "invalid-verification-code": "رمز التفعيل غير صحيح او منتهي الصلاحية",
  "session_expired": "انتهت صلاحية الرمز، يرجى إعادة إرسال رمز التفعيل",
  "you must validate your email first": "يجب تفعيل البريد الالكتروني اولا",
  "sign_up_success": "تم التسجيل بنجاح",
  "OTP_sent_successfully": "تم إرسال رمز التفعيل بنجاح",
  "invalid_verification_code": "رمز التفعيل غير صحيح او منتهي الصلاحية",
};
